// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_eghfhq3gwkPkcbRuVSsfVGGUehynCs',
    appId: '1:137284924681:web:5fc38f797120630c964fd8',
    messagingSenderId: '137284924681',
    projectId: 'student-management-syste-546df',
    authDomain: 'student-management-syste-546df.firebaseapp.com',
    storageBucket: 'student-management-syste-546df.firebasestorage.app',
    measurementId: 'G-ERMVNHVZPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOG39_iM3heDZTiUcTBgqodS0JLxUYR0',
    appId: '1:137284924681:android:d111b9606f214db2964fd8',
    messagingSenderId: '137284924681',
    projectId: 'student-management-syste-546df',
    storageBucket: 'student-management-syste-546df.firebasestorage.app',
  );
}